name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: OVS setup
      run: |
        sudo apt install openvswitch-switch
        sudo ovs-vsctl add-br ovsbr0
        
    - name: Setup enivronment
      run: |
        export GOPATH=/home/runner/work
        export PATH=$PATH:$GOPATH/bin
        mkdir $GOPATH/src $GOPATH/pkg $GOPATH/bin
        go install honnef.co/go/tools/cmd/staticcheck@latest
        NEW=$GOPATH/src/github.com/digitalocean/go-openvswitch
        mkdir -p $NEW
        cp -r ./* $NEW
        cd $NEW
        go mod download
        go get golang.org/x/lint/golint
        go get honnef.co/go/tools/cmd/staticcheck
        go get -d ./...
        ./scripts/licensecheck.sh
        go build -v -tags=gofuzz ./...
        go vet ./...
        staticcheck ./...
        golint -set_exit_status ./cmd/... ./internal/...
        go test -v -race ./ovsnl/
        go test -v -race ./ovsb/
        go test -v -race ./ovsdb/
        go test -c -race ./ovsdb
        sudo ./ovsdb.test -test.v
        go install github.com/praetorian-inc/gokart@latest
        gokart scan