name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: OVS setup
      run: |
        sudo apt install openvswitch-switch
        sudo ovs-vsctl add-br ovsbr0
        
    - name: Get tooling
      run: |
        NEW=$GOPATH/github.com/digitalocean/go-openvswitch
        mkdir -p $NEW
        cp -r ./* $NEW
        cd $NEW
        go get golang.org/x/lint/golint
        go get honnef.co/go/tools/cmd/staticcheck
        go get -d ./...
        
    - name: License check
      run: ./scripts/licensecheck.sh
        
    - name: Build
      run: go build -v -tags=gofuzz ./...

    - name: vet
      run: go vet ./...

    - name: staticcheck
      run: staticcheck ./...

    - name: lint
      run: golint -set_exit_status ./cmd/... ./internal/...

    - name: Test
      run: |
        go test -v -race ./...
        go test -c -race ./ovsdb
        sudo ./ovsdb.test -test.v
